# To understand the following definitions, refer to
# https://www.juniper.net/documentation/en_US/junos-pyez/topics/task/program/junos-pyez-tables-config-defining.html

---
InterfaceConfigTable:
  get: interfaces/interface
  required_keys: 
    interface: name
  view: InterfaceConfigView
InterfaceConfigView:
  fields:
    interface_name: name
    logical_interface: unit/name
    mode: unit/family/ethernet-switching/interface-mode
    vlans: unit/family/ethernet-switching/vlan/members
    native_vlan: native-vlan-id

# Usage: After opening a session to the switch as 'dev'
# do the following:
# from config_tables.ConfigTables import InterfaceConfigTable
# ic = InterfaceConfigTable(dev)
# ic.get(interface= 'et-0/0/11', options = {'database':'committed'}))
# ic.items()
#
